{application,proper,
             [{description,"A QuickCheck-inspired property-based testing tool for Erlang"},
              {maintainers,["Kostis Sagonas"]},
              {licenses,["GPL 3.0"]},
              {links,[{"GitHub","https://github.com/proper-testing/proper"},
                      {"Official Documentation",
                       "https://proper-testing.github.io/"}]},
              {vsn,"1.5.0"},
              {registered,[]},
              {applications,[compiler,kernel,stdlib]},
              {env,[]},
              {modules,[proper,proper_arith,proper_array,proper_dict,
                        proper_erlang_abstract_code,proper_fsm,proper_gb_sets,
                        proper_gb_trees,proper_gen,proper_gen_next,
                        proper_orddict,proper_ordsets,proper_prop_remover,
                        proper_queue,proper_sa,proper_sets,proper_shrink,
                        proper_statem,proper_symb,proper_target,
                        proper_transformer,proper_types,proper_typeserver,
                        proper_unicode,proper_unused_imports_remover,
                        vararg]}]}.
