// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v7.34.1
// source: health.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	HealthService_StreamHealth_FullMethodName = "/health.HealthService/StreamHealth"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HealthService is the bidirectional gRPC service for health streaming.
type HealthServiceClient interface {
	// StreamHealth is a bidirectional stream: Sensor_Agent sends HealthReports,
	// Config_Manager sends acknowledgements or control hints.
	StreamHealth(ctx context.Context, opts ...grpc.CallOption) (HealthService_StreamHealthClient, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) StreamHealth(ctx context.Context, opts ...grpc.CallOption) (HealthService_StreamHealthClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HealthService_ServiceDesc.Streams[0], HealthService_StreamHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &healthServiceStreamHealthClient{ClientStream: stream}
	return x, nil
}

type HealthService_StreamHealthClient interface {
	Send(*HealthReport) error
	Recv() (*HealthAck, error)
	grpc.ClientStream
}

type healthServiceStreamHealthClient struct {
	grpc.ClientStream
}

func (x *healthServiceStreamHealthClient) Send(m *HealthReport) error {
	return x.ClientStream.SendMsg(m)
}

func (x *healthServiceStreamHealthClient) Recv() (*HealthAck, error) {
	m := new(HealthAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility
//
// HealthService is the bidirectional gRPC service for health streaming.
type HealthServiceServer interface {
	// StreamHealth is a bidirectional stream: Sensor_Agent sends HealthReports,
	// Config_Manager sends acknowledgements or control hints.
	StreamHealth(HealthService_StreamHealthServer) error
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHealthServiceServer struct {
}

func (UnimplementedHealthServiceServer) StreamHealth(HealthService_StreamHealthServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamHealth not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_StreamHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HealthServiceServer).StreamHealth(&healthServiceStreamHealthServer{ServerStream: stream})
}

type HealthService_StreamHealthServer interface {
	Send(*HealthAck) error
	Recv() (*HealthReport, error)
	grpc.ServerStream
}

type healthServiceStreamHealthServer struct {
	grpc.ServerStream
}

func (x *healthServiceStreamHealthServer) Send(m *HealthAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *healthServiceStreamHealthServer) Recv() (*HealthReport, error) {
	m := new(HealthReport)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "health.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHealth",
			Handler:       _HealthService_StreamHealth_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "health.proto",
}
